version: "3.3"
services:
  db:
    image: mysql:latest
    container_name: irrigatron_db
    environment:
      MYSQL_ROOT_PASSWORD: thepasswordsupersecreto
      MYSQL_DATABASE: IRRIGATRON
      MYSQL_USER: IRRIGATRON
      MYSQL_PASSWORD: IRRIGATRON
    volumes:
      - /tmp/mysql:/var/lib/mysql
    ports:
      - '3306:3306'
  php-my-admin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: irrigatron_phpmyadmin
    depends_on:
      - db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: thepasswordsupersecreto
      PMA_HOST: irrigatron_db
      PMA_USER: root
      PMA_PASSWORD: thepasswordsupersecreto
    ports:
      - '8081:80'


